[versions]
agp = "8.13.2"
kotlin = "2.2.21"

[libraries]


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

